### ISSUE TITLE
Struggling with compiles and with install

### ISSUE THREAD

**Issue by KJinx101** [Barsay/FL-Studio-SDK-CMake-Template#2]
I was trying to test with the example plug ins, but I could not get them to compile except for Fruity_Gain which was able to ostensibly complete a build. 

The other had 'FATAL ERROR: LNK1104, fl_sdk.lib not found/ opened' [I don't remember exactly, at the moment] and I couldn't get my install of the Fruity Gain to show up in my effects folder which was stated in the doc.

It would be amazing if you could show little bits and pieces at a time of how to set this up and get the examples working in youtube videos / screen recordings. 
Thank you so much! Great work! It got me much farther than the raw API

**Comment by Barsay** [comment]
Unfortunately there still are known problems with the compilation of example plugins, probably due to errors in the CMake template. I will try to fix them in the future.

I will also produce some better documentation soon as well

**Comment by Barsay** [comment]
Last push (5/11/24) fixed the problems for the example plugins: they should now all compile and install successfully. 
Unfortunately plugins themselves still have some bugs that seem to be code-related and not related to compile errors.

Thanks for your feedback!
